######################################################################
# Automatically generated by qmake (2.01a) Do Jan 3 12:26:01 2008
######################################################################

include( ../qrtailab.config )

TEMPLATE = app
TARGET = do_tests
DESTDIR = ../
MOC_DIR           = moc
OBJECTS_DIR       = obj
UI_DIR		  = ui
CONFIG += QwtPlot QwtWidgets qtestlib

# Input

HEADERS += ../src/qrtailab.h ../src/meter_window.h ../src/meters_manager.h ../src/led_window.h ../src/leds_manager.h ../src/scope_window.h ../src/scopes_manager.h ../src/main_window.h ../src/parameters_manager.h ../src/qmeter.h
FORMS += ../src/qrl_connectdialog.ui  ../src/qrl_main_window.ui  ../src/qrl_meters_manager.ui  ../src/qrl_leds_manager.ui  ../src/qrl_scopes_manager.ui ../src/qrl_parameters_manager.ui
SOURCES += ../src/qrtailab.cpp ../src/meter_window.cpp ../src/meters_manager.cpp ../src/led_window.cpp ../src/leds_manager.cpp ../src/scope_window.cpp ../src/scopes_manager.cpp ../src/main_window.cpp ../src/parameters_manager.cpp testgui.cpp ../src/qmeter.cpp ../src/qmeterdrawfunctions.cpp
RESOURCES += ../src/qrtailab.qrc